#!/bin/bash

set +v

current_path="$( dirname "$0" )/"

Rcmd_name1="pre_install_rcmd.r"
Rcmd_path1=$current_path$Rcmd_name1
Rcmd_name2="WIDEa_install_rcmd.r"
Rcmd_path2=$current_path$Rcmd_name2

echo "**Installing the devtools package..."

Rscript "$Rcmd_path1"

echo "Done"
echo;

echo "**Installing the WIDEa package..."

Rscript "$Rcmd_path2"

echo "Done"