#!/bin/bash

echo "Launching WIDEa..."

set +v

current_path="$( dirname "$0" )/"
WIDEa_path="${current_path::${#current_path}-8}"         

WIDEa_Rscript="R_script/WIDEa_launcher.r"
WIDEa_Rscript_path=$WIDEa_path$WIDEa_Rscript

Temp_file_Rscript="R_script/Temporary_file.r"
Temp_file_path=$WIDEa_path$Temp_file_Rscript

Command_part1="rm(list = ls(all = TRUE)); s_WIDEa_path = "
Command_part2="; source("
Command_part3=");"

echo $Command_part1\"$WIDEa_path\"$Command_part2\"$WIDEa_Rscript_path\"$Command_part3 > "$Temp_file_path" 

chflags hidden "$Temp_file_path"

Rscript "$Temp_file_path"

rm -f "$Temp_file_path"